---
version: '2'
services:
  app:
    build: ../maxbook
    depends_on:
      - maxscale
    environment:
      - DATABASE_URL=mysql2://appuser:app-pass@maxscale:3306/maxbook_db
    ports:
      - "3000:3000"
  maxpanel:
    image: skord/maxpanel
    depends_on:
      - maxscale
    environment:
      - MAXSCALE_MAXINFO_JSON_LISTENER_TCP_ADDR=maxscale:8003
    ports:
      - "18080:80"
  maxscale:
    build: maxscale
    command: maxscale -d -l stdout
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - 13306:3306
      - 8003:8003
  influxdb:
    image: influxdb:0.13-alpine
    depends_on:
      - node1
      - node2
      - node3
    expose:
      - 8083
      - 8086
  telegraf:
    image: telegraf
    hostname: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - influxdb
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - '13000:3000'


  node1:
    image: galera
    build: mariadb
    hostname: node1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
    expose:
      - 4567
      - 4567/udp
      - 3306
      - 4444
      - 4568
    command: --skip-name-resolve --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://
  node2:
    extends: node1
    hostname: node2
    depends_on:
      - node1
    command: --skip-name-resolve --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1
  node3:
    extends: node1
    hostname: node3
    depends_on:
      - node1
      - node2
    command: --skip-name-resolve --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1,node2
