---
version: '2'
services:
  app:
    build: ../maxbook
    depends_on:
      - maxscale
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://appuser:app-pass@maxscale:13306/maxbook_db?reaping_frequency=5&dead_connection_timeout=5&pool=1
  maxpanel:
    image: skord/maxpanel
    depends_on:
      - maxscale
    environment:
      - MAXSCALE_MAXINFO_JSON_LISTENER_TCP_ADDR=maxscale:8003
    ports:
      - "18080:80"
  maxscale:
    build: maxscale
    depends_on:
      - replication-manager
    command: maxscale -d -l stdout
    ports:
      - "13306:13306"
      - "13307:13307"
      - "8003:8003"
      - "9003:9003"

  maxscale_exporter:
    build: ../maxscale_exporter
    image: maxscale_exporter
    environment:
      - MAXSCALE_HOST=maxscale
      - MAXSCALE_PORT=9003
      - MAXSCALE_PASSWORD=myreallysecretpassword
      - MAXSCALE_USERNAME=myuser
    depends_on:
      - maxscale
    expose:
      - 9154

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - exporter1
      - exporter2
      - exporter3
      - exporter4
      - exporter5



  grafana:
    image: grafana/grafana
    build: grafana
    depends_on:
      - prometheus
    ports:
      - '13000:3000'
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboard
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboard

  replication-manager:
    image: tanji/replication-manager:latest
    command: monitor --daemon --interactive=false --hosts=mariadb1,mariadb2,mariadb3,mariadb4,mariadb5 --user=root:rootpassword --rpluser=repl:pass --http-server --http-bind-address=0.0.0.0
    depends_on:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
    tty: true
    ports:
      - '10001:10001'
    stdin_open: true

  mariadb1:
    image: mariadb
    build: mariadb
    hostname: mariadb1
    command: --log-bin --skip-name-resolve --server_id=1 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
  agent1:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb1 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb1
  exporter1:
    image: prom/mysqld-exporter
    expose:
      - 9104
    depends_on:
      - mariadb1
    environment:
      - DATA_SOURCE_NAME=exporter:pass@(mariadb1:3306)/
    command:
      - '-collect.perf_schema.eventsstatements=true'
      - '-collect.perf_schema.file_events=true'
      - '-collect.binlog_size=true'
      - '-collect.info_schema.processlist=true'
      - '-collect.info_schema.userstats=true'
      - '-collect.info_schema.tablestats=true'
      - '-collect.info_schema.processlist=true'
      - '-collect.info_schema.innodb_metrics=true'
      - '-collect.info_schema.query_response_time=true'
      - '-collect.perf_schema.eventswaits=true'
      - '-collect.perf_schema.file_events=true'
      - '-collect.perf_schema.indexiowaits=true'
      - '-collect.perf_schema.tableiowaits=true'
      - '-collect.perf_schema.tablelocks=true'


  mariadb2:
    extends: mariadb1
    command: --log-bin --skip-name-resolve --server_id=2 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
  agent2:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb2 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb2
  exporter2:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb2
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb2:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'


  mariadb3:
    extends: mariadb1
    command: --log-bin --skip-name-resolve --server_id=3 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
  agent3:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb3 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb3
  exporter3:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb3
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb3:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'

  mariadb4:
    extends: mariadb1
    command: --log-bin --skip-name-resolve --server_id=4 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
  agent4:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb4 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb4
  exporter4:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb4
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb4:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'

  mariadb5:
    extends: mariadb1
    command: --log-bin --skip-name-resolve --server_id=5 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
  agent5:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb5 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb5
  exporter5:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb5
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb5:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'
